import { type ShapeId } from "@/lib/shapes";

export type ChoiceQ = {
  kind: "choice";
  id: string;
  pack: QuizPack;
  shape?: ShapeId;
  prompt: string;
  hint: string;
  options: string[];
  answer: number;
  explain: string;
};

export type NumericQ = {
  kind: "numeric";
  id: string;
  pack: QuizPack;
  shape?: ShapeId;
  prompt: string;
  hint: string;
  answer: number;
  unit: string;
  explain: string;
};

export type QuizQuestion = ChoiceQ | NumericQ;

export const QUIZ_PACKS = [
  "explorer",
  "perimeter",
  "area",
  "genius",
  "mixed",
] as const;

export type QuizPack = (typeof QUIZ_PACKS)[number] | ShapeId;

export const PACK_META: Record<
  (typeof QUIZ_PACKS)[number],
  { title: string; blurb: string; accent: string }
> = {
  explorer: {
    title: "圖形小偵探",
    blurb: "認邊、認角、認特徵",
    accent: "var(--color-rect)",
  },
  perimeter: {
    title: "周界大挑戰",
    blurb: "走一圈，算一算",
    accent: "var(--color-leaf)",
  },
  area: {
    title: "面積小勇士",
    blurb: "鋪滿格子的魔法",
    accent: "var(--color-coral)",
  },
  genius: {
    title: "原理小博士",
    blurb: "問為什麼，不只問答案",
    accent: "var(--color-hex)",
  },
  mixed: {
    title: "綜合大考驗",
    blurb: "王國總決賽",
    accent: "var(--color-sun)",
  },
};

export const BANK: QuizQuestion[] = [
  {
    kind: "choice",
    id: "e1",
    pack: "explorer",
    shape: "square",
    prompt: "哪一個圖形四條邊一樣長，而且四個角都是直角？",
    hint: "它既是長方形，也是菱形。",
    options: ["長方形", "菱形", "正方形", "梯形"],
    answer: 2,
    explain: "正方形四邊相等、四角都是直角。菱形四邊相等但角不一定是直角；長方形有直角但對邊才相等。",
  },
  {
    kind: "choice",
    id: "e2",
    pack: "explorer",
    shape: "trapezoid",
    prompt: "只有一對平行邊的四邊形，叫做什麼？",
    hint: "想想小桌子或水壩的截面。",
    options: ["平行四邊形", "菱形", "梯形", "長方形"],
    answer: 2,
    explain: "梯形只有一對平行邊（上底和下底）。平行四邊形有兩對平行邊。",
  },
  {
    kind: "choice",
    id: "e3",
    pack: "explorer",
    shape: "circle",
    prompt: "圓形上每一點到哪裡的距離都一樣？",
    hint: "那是圓正中間的一點。",
    options: ["圓周", "直徑", "圓心", "半徑的端點"],
    answer: 2,
    explain: "圓心到圓周上任何一點的距離都相等，這段距離叫半徑。",
  },
  {
    kind: "choice",
    id: "e4",
    pack: "explorer",
    shape: "rhombus",
    prompt: "菱形一定有什麼特徵？",
    hint: "想想四條邊。",
    options: ["四個直角", "四條邊都相等", "只有一對平行邊", "像圓一樣沒有角"],
    answer: 1,
    explain: "菱形四條邊相等。四個角是直角時，它才變成正方形。",
  },
  {
    kind: "choice",
    id: "e5",
    pack: "explorer",
    shape: "parallelogram",
    prompt: "平行四邊形有幾對平行邊？",
    hint: "名字已經提示你了。",
    options: ["0 對", "1 對", "2 對", "3 對"],
    answer: 2,
    explain: "平行四邊形兩對邊分別平行，所以有 2 對平行邊。",
  },
  {
    kind: "choice",
    id: "e6",
    pack: "explorer",
    shape: "triangle",
    prompt: "三角形三個內角加起來是多少度？",
    hint: "把三個角撕下來拼在一條直線上。",
    options: ["90°", "180°", "270°", "360°"],
    answer: 1,
    explain: "任何三角形的內角和都是 180°。把三個角剪下來，可以拼成一條直線。",
  },
  {
    kind: "choice",
    id: "e7",
    pack: "explorer",
    shape: "hexagon",
    prompt: "正六邊形有幾條邊？",
    hint: "蜂巢的每一格。",
    options: ["4", "5", "6", "8"],
    answer: 2,
    explain: "「六」邊形就是有 6 條邊。正六邊形六邊還一樣長。",
  },
  {
    kind: "choice",
    id: "e8",
    pack: "explorer",
    shape: "rectangle",
    prompt: "長方形和正方形相同的地方是？",
    hint: "摸摸它們的角。",
    options: ["四邊一定一樣長", "四個角都是直角", "沒有直角", "只有一對平行邊"],
    answer: 1,
    explain: "兩者四個角都是直角。正方形是長等於闊的長方形。",
  },
  {
    kind: "numeric",
    id: "p1",
    pack: "perimeter",
    shape: "square",
    prompt: "正方形邊長 6 厘米，周界是多少厘米？",
    hint: "四條邊一樣長，乘 4。",
    answer: 24,
    unit: "厘米",
    explain: "周界 = 6 × 4 = 24 厘米。",
  },
  {
    kind: "numeric",
    id: "p2",
    pack: "perimeter",
    shape: "rectangle",
    prompt: "長方形長 8 厘米、闊 3 厘米，周界是多少厘米？",
    hint: "（長 + 闊）× 2。",
    answer: 22,
    unit: "厘米",
    explain: "周界 = (8 + 3) × 2 = 11 × 2 = 22 厘米。",
  },
  {
    kind: "numeric",
    id: "p3",
    pack: "perimeter",
    shape: "triangle",
    prompt: "三角形三邊是 5、6、7 厘米，周界是多少厘米？",
    hint: "三條邊加起來。",
    answer: 18,
    unit: "厘米",
    explain: "周界 = 5 + 6 + 7 = 18 厘米。",
  },
  {
    kind: "numeric",
    id: "p4",
    pack: "perimeter",
    shape: "circle",
    prompt: "圓的半徑是 5 厘米，π = 3.14，圓周是多少厘米？",
    hint: "圓周 = 2 × π × 半徑。",
    answer: 31.4,
    unit: "厘米",
    explain: "圓周 = 2 × 3.14 × 5 = 31.4 厘米。",
  },
  {
    kind: "numeric",
    id: "p5",
    pack: "perimeter",
    shape: "rhombus",
    prompt: "菱形邊長 7 厘米，周界是多少厘米？",
    hint: "菱形四邊相等。",
    answer: 28,
    unit: "厘米",
    explain: "周界 = 7 × 4 = 28 厘米。",
  },
  {
    kind: "numeric",
    id: "p6",
    pack: "perimeter",
    shape: "parallelogram",
    prompt: "平行四邊形底 9 厘米、鄰邊 5 厘米，周界是多少厘米？",
    hint: "兩條底加兩條斜邊。",
    answer: 28,
    unit: "厘米",
    explain: "周界 = (9 + 5) × 2 = 28 厘米。高不用來算周界。",
  },
  {
    kind: "numeric",
    id: "p7",
    pack: "perimeter",
    shape: "trapezoid",
    prompt: "梯形上底 5、下底 11、兩腰各 6 厘米，周界是多少厘米？",
    hint: "四條邊全部相加。",
    answer: 28,
    unit: "厘米",
    explain: "周界 = 5 + 11 + 6 + 6 = 28 厘米。",
  },
  {
    kind: "numeric",
    id: "p8",
    pack: "perimeter",
    shape: "hexagon",
    prompt: "正六邊形邊長 4 厘米，周界是多少厘米？",
    hint: "六條邊。",
    answer: 24,
    unit: "厘米",
    explain: "周界 = 4 × 6 = 24 厘米。",
  },
  {
    kind: "numeric",
    id: "a1",
    pack: "area",
    shape: "square",
    prompt: "正方形邊長 5 厘米，面積是多少平方厘米？",
    hint: "邊長 × 邊長。",
    answer: 25,
    unit: "平方厘米",
    explain: "面積 = 5 × 5 = 25 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a2",
    pack: "area",
    shape: "rectangle",
    prompt: "長方形長 7 厘米、闊 4 厘米，面積是多少平方厘米？",
    hint: "長 × 闊。",
    answer: 28,
    unit: "平方厘米",
    explain: "面積 = 7 × 4 = 28 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a3",
    pack: "area",
    shape: "triangle",
    prompt: "三角形底 10 厘米、高 6 厘米，面積是多少平方厘米？",
    hint: "記得除以 2。",
    answer: 30,
    unit: "平方厘米",
    explain: "面積 = 10 × 6 ÷ 2 = 30 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a4",
    pack: "area",
    shape: "circle",
    prompt: "圓的半徑是 4 厘米，π = 3.14，面積是多少平方厘米？",
    hint: "π × 半徑 × 半徑。",
    answer: 50.24,
    unit: "平方厘米",
    explain: "面積 = 3.14 × 4 × 4 = 3.14 × 16 = 50.24 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a5",
    pack: "area",
    shape: "parallelogram",
    prompt: "平行四邊形底 10 厘米、高 6 厘米，面積是多少平方厘米？",
    hint: "底 × 高，高要垂直。",
    answer: 60,
    unit: "平方厘米",
    explain: "面積 = 10 × 6 = 60 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a6",
    pack: "area",
    shape: "rhombus",
    prompt: "菱形兩條對角線是 6 厘米和 8 厘米，面積是多少平方厘米？",
    hint: "對角線相乘再除以 2。",
    answer: 24,
    unit: "平方厘米",
    explain: "面積 = 6 × 8 ÷ 2 = 24 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a7",
    pack: "area",
    shape: "trapezoid",
    prompt: "梯形上底 5 厘米、下底 9 厘米、高 4 厘米，面積是多少平方厘米？",
    hint: "（上底 + 下底）× 高 ÷ 2。",
    answer: 28,
    unit: "平方厘米",
    explain: "面積 = (5 + 9) × 4 ÷ 2 = 56 ÷ 2 = 28 平方厘米。",
  },
  {
    kind: "numeric",
    id: "a8",
    pack: "area",
    shape: "triangle",
    prompt: "直角三角形兩條直角邊是 8 厘米和 5 厘米，面積是多少平方厘米？",
    hint: "兩條直角邊就是底和高。",
    answer: 20,
    unit: "平方厘米",
    explain: "面積 = 8 × 5 ÷ 2 = 20 平方厘米。",
  },
  {
    kind: "choice",
    id: "g1",
    pack: "genius",
    shape: "triangle",
    prompt: "為什麼三角形面積要除以 2？",
    hint: "想想兩個三角形拼在一起。",
    options: [
      "因為三角形有 3 條邊，3 減 1 等於 2",
      "兩個相同三角形可拼成一個平行四邊形",
      "因為高一定是底的一半",
      "除以 2 比較好看",
    ],
    answer: 1,
    explain: "兩個完全一樣的三角形可以拼成一個平行四邊形（或長方形）。平行四邊形面積是底 × 高，所以一個三角形是一半。",
  },
  {
    kind: "choice",
    id: "g2",
    pack: "genius",
    shape: "parallelogram",
    prompt: "量平行四邊形的高，應該怎樣量？",
    hint: "高像一根直直的柱。",
    options: [
      "沿着斜邊量",
      "兩條底邊之間的垂直距離",
      "隨便量一條對角線",
      "只能量最短的邊",
    ],
    answer: 1,
    explain: "高是兩條平行底邊之間直直（垂直）的距離，不是斜邊。",
  },
  {
    kind: "choice",
    id: "g3",
    pack: "genius",
    shape: "circle",
    prompt: "把圓切成很多薄扇形再一上一下排好，會接近什麼圖形？這能說明圓面積公式。",
    hint: "長乘闊。",
    options: ["三角形", "長方形", "梯形", "菱形"],
    answer: 1,
    explain: "扇形排好後接近長方形：闊 ≈ 半徑 r，長 ≈ πr，所以面積 ≈ πr × r = πr²。",
  },
  {
    kind: "choice",
    id: "g4",
    pack: "genius",
    shape: "trapezoid",
    prompt: "兩個一樣的梯形倒過來拼在一起，會變成什麼？",
    hint: "面積公式裏為什麼要除以 2。",
    options: ["圓", "一個更大的梯形", "平行四邊形", "三角形"],
    answer: 2,
    explain: "兩個相同梯形可拼成平行四邊形，底是上底加下底，所以一個梯形要除以 2。",
  },
  {
    kind: "choice",
    id: "g5",
    pack: "genius",
    shape: "square",
    prompt: "周界和面積有什麼不同？",
    hint: "一個是走一圈，一個是鋪滿。",
    options: [
      "沒有不同，數字一定一樣",
      "周界是走一圈的長度，面積是蓋住多少地",
      "周界用平方厘米，面積用厘米",
      "只有圓才有周界",
    ],
    answer: 1,
    explain: "周界是邊界的總長度（厘米），面積是裏面鋪滿的大小（平方厘米）。",
  },
  {
    kind: "choice",
    id: "g6",
    pack: "genius",
    shape: "rhombus",
    prompt: "菱形的兩條對角線有什麼特別？",
    hint: "它們相交的樣子像十字。",
    options: [
      "一定一樣長",
      "互相垂直平分",
      "永不相交",
      "其中一條一定是高",
    ],
    answer: 1,
    explain: "菱形對角線互相垂直平分。利用這一點，面積 = 對角線相乘 ÷ 2。",
  },
  {
    kind: "choice",
    id: "g7",
    pack: "genius",
    shape: "circle",
    prompt: "圓周率 π 大約是 3.14，它代表什麼意思？",
    hint: "圓周和直徑的關係。",
    options: [
      "圓的面積永遠是 3.14",
      "圓周大約是直徑的 3.14 倍",
      "半徑永遠是 3.14",
      "任何圖形的周界都要乘 3.14",
    ],
    answer: 1,
    explain: "任何圓的圓周 ÷ 直徑都約等於 3.14。所以圓周 = π × 直徑。",
  },
  {
    kind: "choice",
    id: "g8",
    pack: "genius",
    shape: "rectangle",
    prompt: "把平行四邊形左邊的直角三角形剪下，貼到右邊，會變成什麼？面積會變嗎？",
    hint: "只是搬家，沒有丟掉地。",
    options: [
      "變成三角形，面積減半",
      "變成圓，面積變大",
      "變成長方形，面積不變",
      "圖形消失",
    ],
    answer: 2,
    explain: "剪下再貼上只是搬家，面積不變。變成的長方形長是底、闊是高，所以面積 = 底 × 高。",
  },
];

const SHAPE_EXTRA: Record<ShapeId, QuizQuestion[]> = {
  square: [
    {
      kind: "choice",
      id: "sq-c",
      pack: "square",
      shape: "square",
      prompt: "正方形一定也是哪一種圖形？",
      hint: "它的角和邊都很特別。",
      options: ["圓形", "梯形", "長方形", "三角形"],
      answer: 2,
      explain: "正方形有四個直角，所以它是特殊的長方形；四邊相等，也是特殊的菱形。",
    },
    {
      kind: "numeric",
      id: "sq-p",
      pack: "square",
      shape: "square",
      prompt: "正方形邊長 9 厘米，周界是多少厘米？",
      hint: "× 4",
      answer: 36,
      unit: "厘米",
      explain: "9 × 4 = 36 厘米。",
    },
    {
      kind: "numeric",
      id: "sq-a",
      pack: "square",
      shape: "square",
      prompt: "正方形邊長 8 厘米，面積是多少平方厘米？",
      hint: "邊長乘邊長",
      answer: 64,
      unit: "平方厘米",
      explain: "8 × 8 = 64 平方厘米。",
    },
    {
      kind: "choice",
      id: "sq-c2",
      pack: "square",
      shape: "square",
      prompt: "正方形的對角線有什麼特別？",
      hint: "想想對稱。",
      options: ["互相垂直而且等長", "只有一條", "不相等", "一定是曲線"],
      answer: 0,
      explain: "正方形的兩條對角線等長、互相垂直，並且互相平分。",
    },
    {
      kind: "numeric",
      id: "sq-a2",
      pack: "square",
      shape: "square",
      prompt: "正方形周界是 48 厘米，邊長是多少厘米？",
      hint: "周界 ÷ 4",
      answer: 12,
      unit: "厘米",
      explain: "48 ÷ 4 = 12 厘米。",
    },
  ],
  rectangle: [
    {
      kind: "choice",
      id: "rc-c",
      pack: "rectangle",
      shape: "rectangle",
      prompt: "長方形的對邊有什麼關係？",
      hint: "長對長，闊對闊。",
      options: ["對邊相等而且平行", "對邊一定不相等", "只有一對平行", "沒有直角"],
      answer: 0,
      explain: "長方形對邊相等且平行，四個角都是直角。",
    },
    {
      kind: "numeric",
      id: "rc-p",
      pack: "rectangle",
      shape: "rectangle",
      prompt: "長 12 厘米、闊 5 厘米的長方形，周界是多少厘米？",
      hint: "(12+5)×2",
      answer: 34,
      unit: "厘米",
      explain: "(12 + 5) × 2 = 34 厘米。",
    },
    {
      kind: "numeric",
      id: "rc-a",
      pack: "rectangle",
      shape: "rectangle",
      prompt: "長 9 厘米、闊 6 厘米的長方形，面積是多少平方厘米？",
      hint: "長 × 闊",
      answer: 54,
      unit: "平方厘米",
      explain: "9 × 6 = 54 平方厘米。",
    },
    {
      kind: "choice",
      id: "rc-c2",
      pack: "rectangle",
      shape: "rectangle",
      prompt: "長方形一定有幾個直角？",
      hint: "數一數四個角。",
      options: ["2 個", "3 個", "4 個", "不一定"],
      answer: 2,
      explain: "長方形的四個角都是直角。",
    },
    {
      kind: "numeric",
      id: "rc-a2",
      pack: "rectangle",
      shape: "rectangle",
      prompt: "長方形面積 36 平方厘米，闊 4 厘米，長是多少厘米？",
      hint: "面積 ÷ 闊",
      answer: 9,
      unit: "厘米",
      explain: "36 ÷ 4 = 9 厘米。",
    },
  ],
  triangle: [
    {
      kind: "choice",
      id: "tr-c",
      pack: "triangle",
      shape: "triangle",
      prompt: "三角形的『高』是指什麼？",
      hint: "要垂直。",
      options: ["最長的邊", "從頂點垂直落到底的距離", "任意一條邊", "三邊的平均"],
      answer: 1,
      explain: "高是從對面頂點垂直落到底（或底的延長線）的距離。",
    },
    {
      kind: "numeric",
      id: "tr-p",
      pack: "triangle",
      shape: "triangle",
      prompt: "等邊三角形邊長 8 厘米，周界是多少厘米？",
      hint: "三邊相同。",
      answer: 24,
      unit: "厘米",
      explain: "8 × 3 = 24 厘米。",
    },
    {
      kind: "numeric",
      id: "tr-a",
      pack: "triangle",
      shape: "triangle",
      prompt: "底 12 厘米、高 5 厘米的三角形，面積是多少平方厘米？",
      hint: "記得 ÷ 2",
      answer: 30,
      unit: "平方厘米",
      explain: "12 × 5 ÷ 2 = 30 平方厘米。",
    },
    {
      kind: "choice",
      id: "tr-c2",
      pack: "triangle",
      shape: "triangle",
      prompt: "三角形內角和是多少度？",
      hint: "三個角加起來。",
      options: ["90°", "180°", "270°", "360°"],
      answer: 1,
      explain: "任何三角形的三個內角加起來都是 180°。",
    },
    {
      kind: "numeric",
      id: "tr-p2",
      pack: "triangle",
      shape: "triangle",
      prompt: "三邊分別是 5、7、9 厘米的三角形，周界是多少厘米？",
      hint: "三邊相加",
      answer: 21,
      unit: "厘米",
      explain: "5 + 7 + 9 = 21 厘米。",
    },
  ],
  circle: [
    {
      kind: "choice",
      id: "ci-c",
      pack: "circle",
      shape: "circle",
      prompt: "直徑和半徑的關係是？",
      hint: "直徑穿過圓心。",
      options: ["直徑 = 半徑", "直徑 = 半徑 × 2", "直徑 = 半徑 × π", "直徑 = 半徑 ÷ 2"],
      answer: 1,
      explain: "直徑是半徑的 2 倍，也是圓最長的弦。",
    },
    {
      kind: "numeric",
      id: "ci-p",
      pack: "circle",
      shape: "circle",
      prompt: "圓的直徑是 10 厘米，π = 3.14，圓周是多少厘米？",
      hint: "π × 直徑",
      answer: 31.4,
      unit: "厘米",
      explain: "圓周 = 3.14 × 10 = 31.4 厘米。",
    },
    {
      kind: "numeric",
      id: "ci-a",
      pack: "circle",
      shape: "circle",
      prompt: "圓的半徑是 10 厘米，π = 3.14，面積是多少平方厘米？",
      hint: "3.14 × 10 × 10",
      answer: 314,
      unit: "平方厘米",
      explain: "3.14 × 10 × 10 = 314 平方厘米。",
    },
    {
      kind: "choice",
      id: "ci-c2",
      pack: "circle",
      shape: "circle",
      prompt: "半徑是 7 厘米，直徑是多少厘米？",
      hint: "直徑是半徑的兩倍。",
      options: ["3.5 厘米", "7 厘米", "14 厘米", "21 厘米"],
      answer: 2,
      explain: "直徑 = 半徑 × 2 = 14 厘米。",
    },
    {
      kind: "numeric",
      id: "ci-p2",
      pack: "circle",
      shape: "circle",
      prompt: "圓的半徑是 5 厘米，π = 3.14，圓周約是多少厘米？",
      hint: "2 × π × 半徑",
      answer: 31.4,
      unit: "厘米",
      explain: "2 × 3.14 × 5 = 31.4 厘米。",
    },
  ],
  parallelogram: [
    {
      kind: "choice",
      id: "pa-c",
      pack: "parallelogram",
      shape: "parallelogram",
      prompt: "算平行四邊形面積時，不能用哪一條來當高？",
      hint: "斜斜的那條。",
      options: ["垂直高度", "斜邊", "底邊對應的垂直距離", "兩底之間的直距離"],
      answer: 1,
      explain: "斜邊是邊長，用來算周界。高必須垂直於底。",
    },
    {
      kind: "numeric",
      id: "pa-p",
      pack: "parallelogram",
      shape: "parallelogram",
      prompt: "底 8 厘米、鄰邊 6 厘米的平行四邊形，周界是多少厘米？",
      hint: "(8+6)×2",
      answer: 28,
      unit: "厘米",
      explain: "(8 + 6) × 2 = 28 厘米。",
    },
    {
      kind: "numeric",
      id: "pa-a",
      pack: "parallelogram",
      shape: "parallelogram",
      prompt: "底 11 厘米、高 4 厘米的平行四邊形，面積是多少平方厘米？",
      hint: "底 × 高",
      answer: 44,
      unit: "平方厘米",
      explain: "11 × 4 = 44 平方厘米。",
    },
    {
      kind: "choice",
      id: "pa-c2",
      pack: "parallelogram",
      shape: "parallelogram",
      prompt: "平行四邊形有幾對平行邊？",
      hint: "名字裏有『平行』。",
      options: ["一對", "兩對", "三對", "沒有平行邊"],
      answer: 1,
      explain: "平行四邊形有兩對平行邊，對邊相等。",
    },
    {
      kind: "numeric",
      id: "pa-a2",
      pack: "parallelogram",
      shape: "parallelogram",
      prompt: "底 15 厘米、高 6 厘米的平行四邊形，面積是多少平方厘米？",
      hint: "底 × 高",
      answer: 90,
      unit: "平方厘米",
      explain: "15 × 6 = 90 平方厘米。",
    },
  ],
  rhombus: [
    {
      kind: "choice",
      id: "rh-c",
      pack: "rhombus",
      shape: "rhombus",
      prompt: "菱形和正方形最明顯的分別是？",
      hint: "看看角。",
      options: [
        "菱形四邊不相等",
        "正方形四個角都是直角，菱形不一定",
        "菱形沒有對角線",
        "正方形不是平行四邊形",
      ],
      answer: 1,
      explain: "兩者四邊都相等。正方形四個角是直角；普通菱形的角可以是斜的。",
    },
    {
      kind: "numeric",
      id: "rh-p",
      pack: "rhombus",
      shape: "rhombus",
      prompt: "菱形邊長 9 厘米，周界是多少厘米？",
      hint: "× 4",
      answer: 36,
      unit: "厘米",
      explain: "9 × 4 = 36 厘米。",
    },
    {
      kind: "numeric",
      id: "rh-a",
      pack: "rhombus",
      shape: "rhombus",
      prompt: "菱形底 8 厘米、高 5 厘米，面積是多少平方厘米？",
      hint: "底 × 高",
      answer: 40,
      unit: "平方厘米",
      explain: "8 × 5 = 40 平方厘米。",
    },
    {
      kind: "choice",
      id: "rh-c2",
      pack: "rhombus",
      shape: "rhombus",
      prompt: "菱形的四條邊有什麼關係？",
      hint: "全部一樣。",
      options: ["只有對邊相等", "四邊都相等", "鄰邊一定不等", "沒有相等的邊"],
      answer: 1,
      explain: "菱形的四條邊長度都相等。",
    },
    {
      kind: "numeric",
      id: "rh-p2",
      pack: "rhombus",
      shape: "rhombus",
      prompt: "菱形周界 40 厘米，邊長是多少厘米？",
      hint: "周界 ÷ 4",
      answer: 10,
      unit: "厘米",
      explain: "40 ÷ 4 = 10 厘米。",
    },
  ],
  trapezoid: [
    {
      kind: "choice",
      id: "tp-c",
      pack: "trapezoid",
      shape: "trapezoid",
      prompt: "梯形的上底和下底是指什麼？",
      hint: "平行的那一對。",
      options: ["兩條腰", "兩條平行邊", "兩條對角線", "高的兩端"],
      answer: 1,
      explain: "上底、下底是梯形那一對平行邊。",
    },
    {
      kind: "numeric",
      id: "tp-p",
      pack: "trapezoid",
      shape: "trapezoid",
      prompt: "上底 4、下底 10、兩腰 5 和 7 厘米，周界是多少厘米？",
      hint: "四邊相加",
      answer: 26,
      unit: "厘米",
      explain: "4 + 10 + 5 + 7 = 26 厘米。",
    },
    {
      kind: "numeric",
      id: "tp-a",
      pack: "trapezoid",
      shape: "trapezoid",
      prompt: "上底 6、下底 10、高 5 厘米的梯形，面積是多少平方厘米？",
      hint: "(6+10)×5÷2",
      answer: 40,
      unit: "平方厘米",
      explain: "(6 + 10) × 5 ÷ 2 = 40 平方厘米。",
    },
    {
      kind: "choice",
      id: "tp-c2",
      pack: "trapezoid",
      shape: "trapezoid",
      prompt: "梯形面積公式是？",
      hint: "兩個底加起來再……",
      options: ["上底 × 下底", "(上底 + 下底) × 高 ÷ 2", "上底 × 高", "四邊相加"],
      answer: 1,
      explain: "梯形面積 = (上底 + 下底) × 高 ÷ 2。",
    },
    {
      kind: "numeric",
      id: "tp-a2",
      pack: "trapezoid",
      shape: "trapezoid",
      prompt: "上底 5、下底 9、高 4 厘米的梯形，面積是多少平方厘米？",
      hint: "(5+9)×4÷2",
      answer: 28,
      unit: "平方厘米",
      explain: "(5 + 9) × 4 ÷ 2 = 28 平方厘米。",
    },
  ],
  hexagon: [
    {
      kind: "choice",
      id: "hx-c",
      pack: "hexagon",
      shape: "hexagon",
      prompt: "正六邊形可以從中心分成幾個等邊三角形？",
      hint: "有幾條邊就有幾個。",
      options: ["3 個", "4 個", "6 個", "8 個"],
      answer: 2,
      explain: "連到六個頂點，正好分成 6 個等邊三角形。這是面積公式的原理。",
    },
    {
      kind: "numeric",
      id: "hx-p",
      pack: "hexagon",
      shape: "hexagon",
      prompt: "正六邊形邊長 5 厘米，周界是多少厘米？",
      hint: "× 6",
      answer: 30,
      unit: "厘米",
      explain: "5 × 6 = 30 厘米。",
    },
    {
      kind: "choice",
      id: "hx-a",
      pack: "hexagon",
      shape: "hexagon",
      prompt: "為什麼蜂巢用正六邊形？",
      hint: "鋪滿、省蠟。",
      options: [
        "因為蜜蜂不會畫圓",
        "能緊緊鋪滿，而且用較少材料圍出較大空間",
        "六邊形面積公式最簡單",
        "只有六邊形才有周界",
      ],
      answer: 1,
      explain: "正六邊形可以無縫鋪滿平面，又比正方形、三角形更節省圍牆。",
    },
    {
      kind: "choice",
      id: "hx-c2",
      pack: "hexagon",
      shape: "hexagon",
      prompt: "正六邊形有幾條邊？",
      hint: "『六』邊形。",
      options: ["4 條", "5 條", "6 條", "8 條"],
      answer: 2,
      explain: "正六邊形有六條相等的邊和六個相等的角。",
    },
    {
      kind: "numeric",
      id: "hx-p2",
      pack: "hexagon",
      shape: "hexagon",
      prompt: "正六邊形邊長 7 厘米，周界是多少厘米？",
      hint: "× 6",
      answer: 42,
      unit: "厘米",
      explain: "7 × 6 = 42 厘米。",
    },
  ],
};

export function questionsFor(pack: string): QuizQuestion[] {
  if (pack in SHAPE_EXTRA) return SHAPE_EXTRA[pack as ShapeId];
  if (pack === "mixed") {
    return [
      BANK.find((q) => q.id === "e1")!,
      BANK.find((q) => q.id === "p2")!,
      BANK.find((q) => q.id === "a3")!,
      BANK.find((q) => q.id === "g1")!,
      BANK.find((q) => q.id === "p4")!,
      BANK.find((q) => q.id === "a7")!,
      BANK.find((q) => q.id === "g2")!,
      BANK.find((q) => q.id === "e4")!,
    ];
  }
  return BANK.filter((q) => q.pack === pack);
}
