/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as LabRouteImport } from './routes/lab'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ApiArenaRouteImport } from './routes/api/arena'
import { Route as ArenaJoinRouteImport } from './routes/arena_.join'
import { Route as PracticePackRouteImport } from './routes/practice_.$pack'
import { Route as ShapesShapeIdRouteImport } from './routes/shapes.$shapeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArenaRoute = ApiArenaRouteImport.update({
  id: '/api/arena',
  path: '/api/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaJoinRoute = ArenaJoinRouteImport.update({
  id: '/arena_/join',
  path: '/arena/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePackRoute = PracticePackRouteImport.update({
  id: '/practice_/$pack',
  path: '/practice/$pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapesShapeIdRoute = ShapesShapeIdRouteImport.update({
  id: '/shapes/$shapeId',
  path: '/shapes/$shapeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/lab': typeof LabRoute
  '/practice': typeof PracticeRoute
  '/api/arena': typeof ApiArenaRoute
  '/arena/join': typeof ArenaJoinRoute
  '/practice/$pack': typeof PracticePackRoute
  '/shapes/$shapeId': typeof ShapesShapeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/lab': typeof LabRoute
  '/practice': typeof PracticeRoute
  '/api/arena': typeof ApiArenaRoute
  '/arena/join': typeof ArenaJoinRoute
  '/practice/$pack': typeof PracticePackRoute
  '/shapes/$shapeId': typeof ShapesShapeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/lab': typeof LabRoute
  '/practice': typeof PracticeRoute
  '/api/arena': typeof ApiArenaRoute
  '/arena_/join': typeof ArenaJoinRoute
  '/practice_/$pack': typeof PracticePackRoute
  '/shapes/$shapeId': typeof ShapesShapeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/lab'
    | '/practice'
    | '/api/arena'
    | '/arena/join'
    | '/practice/$pack'
    | '/shapes/$shapeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/lab'
    | '/practice'
    | '/api/arena'
    | '/arena/join'
    | '/practice/$pack'
    | '/shapes/$shapeId'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/lab'
    | '/practice'
    | '/api/arena'
    | '/arena_/join'
    | '/practice_/$pack'
    | '/shapes/$shapeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  LabRoute: typeof LabRoute
  PracticeRoute: typeof PracticeRoute
  ApiArenaRoute: typeof ApiArenaRoute
  ArenaJoinRoute: typeof ArenaJoinRoute
  PracticePackRoute: typeof PracticePackRoute
  ShapesShapeIdRoute: typeof ShapesShapeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arena': {
      id: '/api/arena'
      path: '/api/arena'
      fullPath: '/api/arena'
      preLoaderRoute: typeof ApiArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena_/join': {
      id: '/arena_/join'
      path: '/arena/join'
      fullPath: '/arena/join'
      preLoaderRoute: typeof ArenaJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/$pack': {
      id: '/practice_/$pack'
      path: '/practice/$pack'
      fullPath: '/practice/$pack'
      preLoaderRoute: typeof PracticePackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shapes/$shapeId': {
      id: '/shapes/$shapeId'
      path: '/shapes/$shapeId'
      fullPath: '/shapes/$shapeId'
      preLoaderRoute: typeof ShapesShapeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  LabRoute: LabRoute,
  PracticeRoute: PracticeRoute,
  ApiArenaRoute: ApiArenaRoute,
  ArenaJoinRoute: ArenaJoinRoute,
  PracticePackRoute: PracticePackRoute,
  ShapesShapeIdRoute: ShapesShapeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
